# Generated by Django 5.1 on 2024-09-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_bank_branch_bank_location_branch_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmanager',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
        ),
    ]
