# Generated by Django 5.1 on 2024-09-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_account_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='home',
            new_name='bank',
        ),
    ]
